# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.agent import Agent
from ...types.instance_details import InstanceDetails
from .raw_client import AsyncRawAgentsClient, RawAgentsClient

if typing.TYPE_CHECKING:
    from .instructions.client import AsyncInstructionsClient, InstructionsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._instructions: typing.Optional[InstructionsClient] = None

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def create(
        self,
        *,
        name: str,
        enrollment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        instance_details: typing.Optional[InstanceDetails] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Agent:
        """
        Parameters
        ----------
        name : str

        enrollment_ids : typing.Optional[typing.Sequence[str]]

        instance_details : typing.Optional[InstanceDetails]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Agent created

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.agents.create(
            name="name",
        )
        """
        _response = self._raw_client.create(
            name=name, enrollment_ids=enrollment_ids, instance_details=instance_details, request_options=request_options
        )
        return _response.data

    def get(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Agent:
        """
        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Agent found

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.agents.get(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.get(agent_id, request_options=request_options)
        return _response.data

    def delete(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.agents.delete(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.delete(agent_id, request_options=request_options)
        return _response.data

    def update(
        self,
        agent_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        enrollment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        instance_details: typing.Optional[InstanceDetails] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Agent:
        """
        Parameters
        ----------
        agent_id : str

        name : typing.Optional[str]

        enrollment_ids : typing.Optional[typing.Sequence[str]]

        instance_details : typing.Optional[InstanceDetails]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Agent updated

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.agents.update(
            agent_id="agent_id",
        )
        """
        _response = self._raw_client.update(
            agent_id,
            name=name,
            enrollment_ids=enrollment_ids,
            instance_details=instance_details,
            request_options=request_options,
        )
        return _response.data

    @property
    def instructions(self):
        if self._instructions is None:
            from .instructions.client import InstructionsClient  # noqa: E402

            self._instructions = InstructionsClient(client_wrapper=self._client_wrapper)
        return self._instructions


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._instructions: typing.Optional[AsyncInstructionsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        name: str,
        enrollment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        instance_details: typing.Optional[InstanceDetails] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Agent:
        """
        Parameters
        ----------
        name : str

        enrollment_ids : typing.Optional[typing.Sequence[str]]

        instance_details : typing.Optional[InstanceDetails]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Agent created

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.agents.create(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name, enrollment_ids=enrollment_ids, instance_details=instance_details, request_options=request_options
        )
        return _response.data

    async def get(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Agent:
        """
        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Agent found

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.agents.get(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(agent_id, request_options=request_options)
        return _response.data

    async def delete(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.agents.delete(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(agent_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        agent_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        enrollment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        instance_details: typing.Optional[InstanceDetails] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Agent:
        """
        Parameters
        ----------
        agent_id : str

        name : typing.Optional[str]

        enrollment_ids : typing.Optional[typing.Sequence[str]]

        instance_details : typing.Optional[InstanceDetails]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Agent updated

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.agents.update(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            agent_id,
            name=name,
            enrollment_ids=enrollment_ids,
            instance_details=instance_details,
            request_options=request_options,
        )
        return _response.data

    @property
    def instructions(self):
        if self._instructions is None:
            from .instructions.client import AsyncInstructionsClient  # noqa: E402

            self._instructions = AsyncInstructionsClient(client_wrapper=self._client_wrapper)
        return self._instructions
