# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.device_context import DeviceContext
from ....types.enrollment import Enrollment
from ....types.verification_response import VerificationResponse
from .raw_client import AsyncRawVerifyClient, RawVerifyClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VerifyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVerifyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVerifyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVerifyClient
        """
        return self._raw_client

    def start(
        self,
        enrollment_id: str,
        *,
        device_context: DeviceContext,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VerificationResponse:
        """
        Initiates the cardholder verification flow for a pending enrollment.

        Parameters
        ----------
        enrollment_id : str

        device_context : DeviceContext

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerificationResponse
            Verification started — returns available methods or passkey options

        Examples
        --------
        from basis_theory import BasisTheory, DeviceContext

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.enrollments.verify.start(
            enrollment_id="enrollment_id",
            device_context=DeviceContext(
                screen_height=1,
                screen_width=1,
                user_agent_string="user_agent_string",
                language_code="language_code",
                time_zone="time_zone",
                java_script_enabled=True,
                client_device_id="client_device_id",
                client_reference_id="client_reference_id",
                platform_type="WEB",
            ),
        )
        """
        _response = self._raw_client.start(
            enrollment_id, device_context=device_context, request_options=request_options
        )
        return _response.data

    def method(
        self, enrollment_id: str, *, method_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VerificationResponse:
        """
        Choose the OTP delivery method (SMS, email, etc.) for enrollment verification.

        Parameters
        ----------
        enrollment_id : str

        method_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerificationResponse
            OTP method selected — OTP sent to cardholder

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.enrollments.verify.method(
            enrollment_id="enrollment_id",
            method_id="method_id",
        )
        """
        _response = self._raw_client.method(enrollment_id, method_id=method_id, request_options=request_options)
        return _response.data

    def otp(
        self, enrollment_id: str, *, otp_code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Enrollment:
        """
        Submit the one-time password received by the cardholder.

        Parameters
        ----------
        enrollment_id : str

        otp_code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Enrollment
            OTP accepted — enrollment verified or next step returned

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.enrollments.verify.otp(
            enrollment_id="enrollment_id",
            otp_code="otp_code",
        )
        """
        _response = self._raw_client.otp(enrollment_id, otp_code=otp_code, request_options=request_options)
        return _response.data

    def complete(
        self,
        enrollment_id: str,
        *,
        assurance_data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        src_correlation_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Enrollment:
        """
        Complete the verification flow (e.g. after passkey creation). Body is optional — Visa sends empty body, Mastercard sends assurance_data.

        Parameters
        ----------
        enrollment_id : str

        assurance_data : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        src_correlation_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Enrollment
            Verification completed — enrollment is now active

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.enrollments.verify.complete(
            enrollment_id="enrollment_id",
        )
        """
        _response = self._raw_client.complete(
            enrollment_id,
            assurance_data=assurance_data,
            src_correlation_id=src_correlation_id,
            request_options=request_options,
        )
        return _response.data


class AsyncVerifyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVerifyClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVerifyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVerifyClient
        """
        return self._raw_client

    async def start(
        self,
        enrollment_id: str,
        *,
        device_context: DeviceContext,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VerificationResponse:
        """
        Initiates the cardholder verification flow for a pending enrollment.

        Parameters
        ----------
        enrollment_id : str

        device_context : DeviceContext

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerificationResponse
            Verification started — returns available methods or passkey options

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory, DeviceContext

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.enrollments.verify.start(
                enrollment_id="enrollment_id",
                device_context=DeviceContext(
                    screen_height=1,
                    screen_width=1,
                    user_agent_string="user_agent_string",
                    language_code="language_code",
                    time_zone="time_zone",
                    java_script_enabled=True,
                    client_device_id="client_device_id",
                    client_reference_id="client_reference_id",
                    platform_type="WEB",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start(
            enrollment_id, device_context=device_context, request_options=request_options
        )
        return _response.data

    async def method(
        self, enrollment_id: str, *, method_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VerificationResponse:
        """
        Choose the OTP delivery method (SMS, email, etc.) for enrollment verification.

        Parameters
        ----------
        enrollment_id : str

        method_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerificationResponse
            OTP method selected — OTP sent to cardholder

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.enrollments.verify.method(
                enrollment_id="enrollment_id",
                method_id="method_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.method(enrollment_id, method_id=method_id, request_options=request_options)
        return _response.data

    async def otp(
        self, enrollment_id: str, *, otp_code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Enrollment:
        """
        Submit the one-time password received by the cardholder.

        Parameters
        ----------
        enrollment_id : str

        otp_code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Enrollment
            OTP accepted — enrollment verified or next step returned

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.enrollments.verify.otp(
                enrollment_id="enrollment_id",
                otp_code="otp_code",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.otp(enrollment_id, otp_code=otp_code, request_options=request_options)
        return _response.data

    async def complete(
        self,
        enrollment_id: str,
        *,
        assurance_data: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        src_correlation_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Enrollment:
        """
        Complete the verification flow (e.g. after passkey creation). Body is optional — Visa sends empty body, Mastercard sends assurance_data.

        Parameters
        ----------
        enrollment_id : str

        assurance_data : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        src_correlation_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Enrollment
            Verification completed — enrollment is now active

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.enrollments.verify.complete(
                enrollment_id="enrollment_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.complete(
            enrollment_id,
            assurance_data=assurance_data,
            src_correlation_id=src_correlation_id,
            request_options=request_options,
        )
        return _response.data
