# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.allowance import Allowance
from .raw_client import AsyncRawRailsClient, RawRailsClient
from .types.rails_retry_request_provider import RailsRetryRequestProvider
from .types.rails_retry_request_rail import RailsRetryRequestRail

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RailsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRailsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRailsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRailsClient
        """
        return self._raw_client

    def retry(
        self,
        allowance_id: str,
        *,
        rail: RailsRetryRequestRail,
        provider: RailsRetryRequestProvider,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Allowance:
        """
        Re-run provider setup for one failed allowance rail. Allowance creation keeps rails that failed at the provider, so a transient outage does not require rebuilding the mandate. Only rails with status `error` can be retried, and the payment method's matching rail must still be `enabled`.

        Parameters
        ----------
        allowance_id : str

        rail : RailsRetryRequestRail

        provider : RailsRetryRequestProvider

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Allowance
            Allowance with updated rail state

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.agentic.allowances.rails.retry(
            allowance_id="allowance_id",
            rail="agentic-token",
            provider="vic",
        )
        """
        _response = self._raw_client.retry(allowance_id, rail=rail, provider=provider, request_options=request_options)
        return _response.data


class AsyncRailsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRailsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRailsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRailsClient
        """
        return self._raw_client

    async def retry(
        self,
        allowance_id: str,
        *,
        rail: RailsRetryRequestRail,
        provider: RailsRetryRequestProvider,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Allowance:
        """
        Re-run provider setup for one failed allowance rail. Allowance creation keeps rails that failed at the provider, so a transient outage does not require rebuilding the mandate. Only rails with status `error` can be retried, and the payment method's matching rail must still be `enabled`.

        Parameters
        ----------
        allowance_id : str

        rail : RailsRetryRequestRail

        provider : RailsRetryRequestProvider

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Allowance
            Allowance with updated rail state

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.agentic.allowances.rails.retry(
                allowance_id="allowance_id",
                rail="agentic-token",
                provider="vic",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retry(
            allowance_id, rail=rail, provider=provider, request_options=request_options
        )
        return _response.data
