# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import AllowancesListRequestStatus
    from . import credentials, rails
    from .credentials import (
        CardCreatePaymentCredentialRequestCredential,
        CreatePaymentCredentialRequestCredential,
        CreatePaymentCredentialRequestCredentialCard,
        CreatePaymentCredentialRequestCredentialIdentifier,
        CreatePaymentCredentialRequestCredentialIdentifierPayload,
        CreatePaymentCredentialRequestCredentialMpp,
        CreatePaymentCredentialRequestCredentialMppPayload,
        CreatePaymentCredentialRequestCredentialMppPayloadBillingAddress,
        CreatePaymentCredentialRequestCredentialMppPayloadChallenge,
        CreatePaymentCredentialRequestCredentialMppPayloadChallengeMethod,
        CreatePaymentCredentialRequestCredentialNetworkToken,
        CreatePaymentCredentialRequestProvider,
        CreatePaymentCredentialRequestRail,
        IdentifierCreatePaymentCredentialRequestCredential,
        MppCreatePaymentCredentialRequestCredential,
        NetworkTokenCreatePaymentCredentialRequestCredential,
    )
    from .rails import RailsRetryRequestProvider, RailsRetryRequestRail
_dynamic_imports: typing.Dict[str, str] = {
    "AllowancesListRequestStatus": ".types",
    "CardCreatePaymentCredentialRequestCredential": ".credentials",
    "CreatePaymentCredentialRequestCredential": ".credentials",
    "CreatePaymentCredentialRequestCredentialCard": ".credentials",
    "CreatePaymentCredentialRequestCredentialIdentifier": ".credentials",
    "CreatePaymentCredentialRequestCredentialIdentifierPayload": ".credentials",
    "CreatePaymentCredentialRequestCredentialMpp": ".credentials",
    "CreatePaymentCredentialRequestCredentialMppPayload": ".credentials",
    "CreatePaymentCredentialRequestCredentialMppPayloadBillingAddress": ".credentials",
    "CreatePaymentCredentialRequestCredentialMppPayloadChallenge": ".credentials",
    "CreatePaymentCredentialRequestCredentialMppPayloadChallengeMethod": ".credentials",
    "CreatePaymentCredentialRequestCredentialNetworkToken": ".credentials",
    "CreatePaymentCredentialRequestProvider": ".credentials",
    "CreatePaymentCredentialRequestRail": ".credentials",
    "IdentifierCreatePaymentCredentialRequestCredential": ".credentials",
    "MppCreatePaymentCredentialRequestCredential": ".credentials",
    "NetworkTokenCreatePaymentCredentialRequestCredential": ".credentials",
    "RailsRetryRequestProvider": ".rails",
    "RailsRetryRequestRail": ".rails",
    "credentials": ".credentials",
    "rails": ".rails",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AllowancesListRequestStatus",
    "CardCreatePaymentCredentialRequestCredential",
    "CreatePaymentCredentialRequestCredential",
    "CreatePaymentCredentialRequestCredentialCard",
    "CreatePaymentCredentialRequestCredentialIdentifier",
    "CreatePaymentCredentialRequestCredentialIdentifierPayload",
    "CreatePaymentCredentialRequestCredentialMpp",
    "CreatePaymentCredentialRequestCredentialMppPayload",
    "CreatePaymentCredentialRequestCredentialMppPayloadBillingAddress",
    "CreatePaymentCredentialRequestCredentialMppPayloadChallenge",
    "CreatePaymentCredentialRequestCredentialMppPayloadChallengeMethod",
    "CreatePaymentCredentialRequestCredentialNetworkToken",
    "CreatePaymentCredentialRequestProvider",
    "CreatePaymentCredentialRequestRail",
    "IdentifierCreatePaymentCredentialRequestCredential",
    "MppCreatePaymentCredentialRequestCredential",
    "NetworkTokenCreatePaymentCredentialRequestCredential",
    "RailsRetryRequestProvider",
    "RailsRetryRequestRail",
    "credentials",
    "rails",
]
