# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import BasisTheoryEnvironment

if typing.TYPE_CHECKING:
    from .account_updater.client import AccountUpdaterClient, AsyncAccountUpdaterClient
    from .apple_pay.client import ApplePayClient, AsyncApplePayClient
    from .application_keys.client import ApplicationKeysClient, AsyncApplicationKeysClient
    from .application_templates.client import ApplicationTemplatesClient, AsyncApplicationTemplatesClient
    from .applications.client import ApplicationsClient, AsyncApplicationsClient
    from .documents.client import AsyncDocumentsClient, DocumentsClient
    from .enrichments.client import AsyncEnrichmentsClient, EnrichmentsClient
    from .google_pay.client import AsyncGooglePayClient, GooglePayClient
    from .keys.client import AsyncKeysClient, KeysClient
    from .logs.client import AsyncLogsClient, LogsClient
    from .network_tokens.client import AsyncNetworkTokensClient, NetworkTokensClient
    from .permissions.client import AsyncPermissionsClient, PermissionsClient
    from .proxies.client import AsyncProxiesClient, ProxiesClient
    from .reactors.client import AsyncReactorsClient, ReactorsClient
    from .roles.client import AsyncRolesClient, RolesClient
    from .sessions.client import AsyncSessionsClient, SessionsClient
    from .tenants.client import AsyncTenantsClient, TenantsClient
    from .threeds.client import AsyncThreedsClient, ThreedsClient
    from .token_intents.client import AsyncTokenIntentsClient, TokenIntentsClient
    from .tokens.client import AsyncTokensClient, TokensClient
    from .webhooks.client import AsyncWebhooksClient, WebhooksClient


class BasisTheory:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : BasisTheoryEnvironment
        The environment to use for requests from the client. from .environment import BasisTheoryEnvironment



        Defaults to BasisTheoryEnvironment.DEFAULT



    correlation_id : typing.Optional[str]
    api_key : typing.Optional[str]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from basis_theory import BasisTheory

    client = BasisTheory(
        correlation_id="YOUR_CORRELATION_ID",
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: BasisTheoryEnvironment = BasisTheoryEnvironment.DEFAULT,
        correlation_id: typing.Optional[str] = None,
        api_key: typing.Optional[str] = os.getenv("BT-API-KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting BT-API-KEY")
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            correlation_id=correlation_id,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._applications: typing.Optional[ApplicationsClient] = None
        self._application_keys: typing.Optional[ApplicationKeysClient] = None
        self._application_templates: typing.Optional[ApplicationTemplatesClient] = None
        self._apple_pay: typing.Optional[ApplePayClient] = None
        self._google_pay: typing.Optional[GooglePayClient] = None
        self._documents: typing.Optional[DocumentsClient] = None
        self._tokens: typing.Optional[TokensClient] = None
        self._enrichments: typing.Optional[EnrichmentsClient] = None
        self._keys: typing.Optional[KeysClient] = None
        self._logs: typing.Optional[LogsClient] = None
        self._network_tokens: typing.Optional[NetworkTokensClient] = None
        self._permissions: typing.Optional[PermissionsClient] = None
        self._proxies: typing.Optional[ProxiesClient] = None
        self._reactors: typing.Optional[ReactorsClient] = None
        self._roles: typing.Optional[RolesClient] = None
        self._sessions: typing.Optional[SessionsClient] = None
        self._token_intents: typing.Optional[TokenIntentsClient] = None
        self._webhooks: typing.Optional[WebhooksClient] = None
        self._account_updater: typing.Optional[AccountUpdaterClient] = None
        self._tenants: typing.Optional[TenantsClient] = None
        self._threeds: typing.Optional[ThreedsClient] = None

    @property
    def applications(self):
        if self._applications is None:
            from .applications.client import ApplicationsClient  # noqa: E402

            self._applications = ApplicationsClient(client_wrapper=self._client_wrapper)
        return self._applications

    @property
    def application_keys(self):
        if self._application_keys is None:
            from .application_keys.client import ApplicationKeysClient  # noqa: E402

            self._application_keys = ApplicationKeysClient(client_wrapper=self._client_wrapper)
        return self._application_keys

    @property
    def application_templates(self):
        if self._application_templates is None:
            from .application_templates.client import ApplicationTemplatesClient  # noqa: E402

            self._application_templates = ApplicationTemplatesClient(client_wrapper=self._client_wrapper)
        return self._application_templates

    @property
    def apple_pay(self):
        if self._apple_pay is None:
            from .apple_pay.client import ApplePayClient  # noqa: E402

            self._apple_pay = ApplePayClient(client_wrapper=self._client_wrapper)
        return self._apple_pay

    @property
    def google_pay(self):
        if self._google_pay is None:
            from .google_pay.client import GooglePayClient  # noqa: E402

            self._google_pay = GooglePayClient(client_wrapper=self._client_wrapper)
        return self._google_pay

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import DocumentsClient  # noqa: E402

            self._documents = DocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents

    @property
    def tokens(self):
        if self._tokens is None:
            from .tokens.client import TokensClient  # noqa: E402

            self._tokens = TokensClient(client_wrapper=self._client_wrapper)
        return self._tokens

    @property
    def enrichments(self):
        if self._enrichments is None:
            from .enrichments.client import EnrichmentsClient  # noqa: E402

            self._enrichments = EnrichmentsClient(client_wrapper=self._client_wrapper)
        return self._enrichments

    @property
    def keys(self):
        if self._keys is None:
            from .keys.client import KeysClient  # noqa: E402

            self._keys = KeysClient(client_wrapper=self._client_wrapper)
        return self._keys

    @property
    def logs(self):
        if self._logs is None:
            from .logs.client import LogsClient  # noqa: E402

            self._logs = LogsClient(client_wrapper=self._client_wrapper)
        return self._logs

    @property
    def network_tokens(self):
        if self._network_tokens is None:
            from .network_tokens.client import NetworkTokensClient  # noqa: E402

            self._network_tokens = NetworkTokensClient(client_wrapper=self._client_wrapper)
        return self._network_tokens

    @property
    def permissions(self):
        if self._permissions is None:
            from .permissions.client import PermissionsClient  # noqa: E402

            self._permissions = PermissionsClient(client_wrapper=self._client_wrapper)
        return self._permissions

    @property
    def proxies(self):
        if self._proxies is None:
            from .proxies.client import ProxiesClient  # noqa: E402

            self._proxies = ProxiesClient(client_wrapper=self._client_wrapper)
        return self._proxies

    @property
    def reactors(self):
        if self._reactors is None:
            from .reactors.client import ReactorsClient  # noqa: E402

            self._reactors = ReactorsClient(client_wrapper=self._client_wrapper)
        return self._reactors

    @property
    def roles(self):
        if self._roles is None:
            from .roles.client import RolesClient  # noqa: E402

            self._roles = RolesClient(client_wrapper=self._client_wrapper)
        return self._roles

    @property
    def sessions(self):
        if self._sessions is None:
            from .sessions.client import SessionsClient  # noqa: E402

            self._sessions = SessionsClient(client_wrapper=self._client_wrapper)
        return self._sessions

    @property
    def token_intents(self):
        if self._token_intents is None:
            from .token_intents.client import TokenIntentsClient  # noqa: E402

            self._token_intents = TokenIntentsClient(client_wrapper=self._client_wrapper)
        return self._token_intents

    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import WebhooksClient  # noqa: E402

            self._webhooks = WebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks

    @property
    def account_updater(self):
        if self._account_updater is None:
            from .account_updater.client import AccountUpdaterClient  # noqa: E402

            self._account_updater = AccountUpdaterClient(client_wrapper=self._client_wrapper)
        return self._account_updater

    @property
    def tenants(self):
        if self._tenants is None:
            from .tenants.client import TenantsClient  # noqa: E402

            self._tenants = TenantsClient(client_wrapper=self._client_wrapper)
        return self._tenants

    @property
    def threeds(self):
        if self._threeds is None:
            from .threeds.client import ThreedsClient  # noqa: E402

            self._threeds = ThreedsClient(client_wrapper=self._client_wrapper)
        return self._threeds


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncBasisTheory:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : BasisTheoryEnvironment
        The environment to use for requests from the client. from .environment import BasisTheoryEnvironment



        Defaults to BasisTheoryEnvironment.DEFAULT



    correlation_id : typing.Optional[str]
    api_key : typing.Optional[str]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from basis_theory import AsyncBasisTheory

    client = AsyncBasisTheory(
        correlation_id="YOUR_CORRELATION_ID",
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: BasisTheoryEnvironment = BasisTheoryEnvironment.DEFAULT,
        correlation_id: typing.Optional[str] = None,
        api_key: typing.Optional[str] = os.getenv("BT-API-KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting BT-API-KEY")
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            correlation_id=correlation_id,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._applications: typing.Optional[AsyncApplicationsClient] = None
        self._application_keys: typing.Optional[AsyncApplicationKeysClient] = None
        self._application_templates: typing.Optional[AsyncApplicationTemplatesClient] = None
        self._apple_pay: typing.Optional[AsyncApplePayClient] = None
        self._google_pay: typing.Optional[AsyncGooglePayClient] = None
        self._documents: typing.Optional[AsyncDocumentsClient] = None
        self._tokens: typing.Optional[AsyncTokensClient] = None
        self._enrichments: typing.Optional[AsyncEnrichmentsClient] = None
        self._keys: typing.Optional[AsyncKeysClient] = None
        self._logs: typing.Optional[AsyncLogsClient] = None
        self._network_tokens: typing.Optional[AsyncNetworkTokensClient] = None
        self._permissions: typing.Optional[AsyncPermissionsClient] = None
        self._proxies: typing.Optional[AsyncProxiesClient] = None
        self._reactors: typing.Optional[AsyncReactorsClient] = None
        self._roles: typing.Optional[AsyncRolesClient] = None
        self._sessions: typing.Optional[AsyncSessionsClient] = None
        self._token_intents: typing.Optional[AsyncTokenIntentsClient] = None
        self._webhooks: typing.Optional[AsyncWebhooksClient] = None
        self._account_updater: typing.Optional[AsyncAccountUpdaterClient] = None
        self._tenants: typing.Optional[AsyncTenantsClient] = None
        self._threeds: typing.Optional[AsyncThreedsClient] = None

    @property
    def applications(self):
        if self._applications is None:
            from .applications.client import AsyncApplicationsClient  # noqa: E402

            self._applications = AsyncApplicationsClient(client_wrapper=self._client_wrapper)
        return self._applications

    @property
    def application_keys(self):
        if self._application_keys is None:
            from .application_keys.client import AsyncApplicationKeysClient  # noqa: E402

            self._application_keys = AsyncApplicationKeysClient(client_wrapper=self._client_wrapper)
        return self._application_keys

    @property
    def application_templates(self):
        if self._application_templates is None:
            from .application_templates.client import AsyncApplicationTemplatesClient  # noqa: E402

            self._application_templates = AsyncApplicationTemplatesClient(client_wrapper=self._client_wrapper)
        return self._application_templates

    @property
    def apple_pay(self):
        if self._apple_pay is None:
            from .apple_pay.client import AsyncApplePayClient  # noqa: E402

            self._apple_pay = AsyncApplePayClient(client_wrapper=self._client_wrapper)
        return self._apple_pay

    @property
    def google_pay(self):
        if self._google_pay is None:
            from .google_pay.client import AsyncGooglePayClient  # noqa: E402

            self._google_pay = AsyncGooglePayClient(client_wrapper=self._client_wrapper)
        return self._google_pay

    @property
    def documents(self):
        if self._documents is None:
            from .documents.client import AsyncDocumentsClient  # noqa: E402

            self._documents = AsyncDocumentsClient(client_wrapper=self._client_wrapper)
        return self._documents

    @property
    def tokens(self):
        if self._tokens is None:
            from .tokens.client import AsyncTokensClient  # noqa: E402

            self._tokens = AsyncTokensClient(client_wrapper=self._client_wrapper)
        return self._tokens

    @property
    def enrichments(self):
        if self._enrichments is None:
            from .enrichments.client import AsyncEnrichmentsClient  # noqa: E402

            self._enrichments = AsyncEnrichmentsClient(client_wrapper=self._client_wrapper)
        return self._enrichments

    @property
    def keys(self):
        if self._keys is None:
            from .keys.client import AsyncKeysClient  # noqa: E402

            self._keys = AsyncKeysClient(client_wrapper=self._client_wrapper)
        return self._keys

    @property
    def logs(self):
        if self._logs is None:
            from .logs.client import AsyncLogsClient  # noqa: E402

            self._logs = AsyncLogsClient(client_wrapper=self._client_wrapper)
        return self._logs

    @property
    def network_tokens(self):
        if self._network_tokens is None:
            from .network_tokens.client import AsyncNetworkTokensClient  # noqa: E402

            self._network_tokens = AsyncNetworkTokensClient(client_wrapper=self._client_wrapper)
        return self._network_tokens

    @property
    def permissions(self):
        if self._permissions is None:
            from .permissions.client import AsyncPermissionsClient  # noqa: E402

            self._permissions = AsyncPermissionsClient(client_wrapper=self._client_wrapper)
        return self._permissions

    @property
    def proxies(self):
        if self._proxies is None:
            from .proxies.client import AsyncProxiesClient  # noqa: E402

            self._proxies = AsyncProxiesClient(client_wrapper=self._client_wrapper)
        return self._proxies

    @property
    def reactors(self):
        if self._reactors is None:
            from .reactors.client import AsyncReactorsClient  # noqa: E402

            self._reactors = AsyncReactorsClient(client_wrapper=self._client_wrapper)
        return self._reactors

    @property
    def roles(self):
        if self._roles is None:
            from .roles.client import AsyncRolesClient  # noqa: E402

            self._roles = AsyncRolesClient(client_wrapper=self._client_wrapper)
        return self._roles

    @property
    def sessions(self):
        if self._sessions is None:
            from .sessions.client import AsyncSessionsClient  # noqa: E402

            self._sessions = AsyncSessionsClient(client_wrapper=self._client_wrapper)
        return self._sessions

    @property
    def token_intents(self):
        if self._token_intents is None:
            from .token_intents.client import AsyncTokenIntentsClient  # noqa: E402

            self._token_intents = AsyncTokenIntentsClient(client_wrapper=self._client_wrapper)
        return self._token_intents

    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import AsyncWebhooksClient  # noqa: E402

            self._webhooks = AsyncWebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks

    @property
    def account_updater(self):
        if self._account_updater is None:
            from .account_updater.client import AsyncAccountUpdaterClient  # noqa: E402

            self._account_updater = AsyncAccountUpdaterClient(client_wrapper=self._client_wrapper)
        return self._account_updater

    @property
    def tenants(self):
        if self._tenants is None:
            from .tenants.client import AsyncTenantsClient  # noqa: E402

            self._tenants = AsyncTenantsClient(client_wrapper=self._client_wrapper)
        return self._tenants

    @property
    def threeds(self):
        if self._threeds is None:
            from .threeds.client import AsyncThreedsClient  # noqa: E402

            self._threeds = AsyncThreedsClient(client_wrapper=self._client_wrapper)
        return self._threeds


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: BasisTheoryEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
