# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.account_updater_real_time_response import AccountUpdaterRealTimeResponse
from .raw_client import AsyncRawRealTimeClient, RawRealTimeClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RealTimeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRealTimeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRealTimeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRealTimeClient
        """
        return self._raw_client

    def invoke(
        self,
        *,
        token_id: str,
        bt_merchant_id: typing.Optional[str] = None,
        expiration_year: typing.Optional[int] = OMIT,
        expiration_month: typing.Optional[int] = OMIT,
        deduplicate_token: typing.Optional[bool] = OMIT,
        configuration_merchant_id: typing.Optional[str] = OMIT,
        merchant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountUpdaterRealTimeResponse:
        """
        Returns the update result

        Parameters
        ----------
        token_id : str
            Card Token identifier

        bt_merchant_id : typing.Optional[str]
            Tenant merchant the request acts as. The card token is read within this merchant's scope and the updated token is associated with it. Responds 404 if the merchant does not exist in the tenant.

        expiration_year : typing.Optional[int]
            The 4-digit expiration year of the account number. Not required if the card token already stores this value.

        expiration_month : typing.Optional[int]
            The 2-digit expiration month of the account number. Not required if the card token already stores this value.

        deduplicate_token : typing.Optional[bool]
            Whether deduplication should be enabled when creating the new token. Uses the value of the Deduplicate Tokens setting on the tenant if not set.

        configuration_merchant_id : typing.Optional[str]
            Tenant merchant whose provider configuration is used for this request. Selects configuration only; it does not scope token access or associate the new token with the merchant. Takes precedence over merchant_id; defaults to the BT-MERCHANT-ID header merchant, then the tenant-level configuration.

        merchant_id : typing.Optional[str]
            Deprecated: use configuration_merchant_id instead. Legacy alias kept for backward compatibility with lower precedence. Selects configuration only.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountUpdaterRealTimeResponse
            Success

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.account_updater.real_time.invoke(
            token_id="9a420b15-ddfe-4793-9466-48f53520e47c",
        )
        """
        _response = self._raw_client.invoke(
            token_id=token_id,
            bt_merchant_id=bt_merchant_id,
            expiration_year=expiration_year,
            expiration_month=expiration_month,
            deduplicate_token=deduplicate_token,
            configuration_merchant_id=configuration_merchant_id,
            merchant_id=merchant_id,
            request_options=request_options,
        )
        return _response.data


class AsyncRealTimeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRealTimeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRealTimeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRealTimeClient
        """
        return self._raw_client

    async def invoke(
        self,
        *,
        token_id: str,
        bt_merchant_id: typing.Optional[str] = None,
        expiration_year: typing.Optional[int] = OMIT,
        expiration_month: typing.Optional[int] = OMIT,
        deduplicate_token: typing.Optional[bool] = OMIT,
        configuration_merchant_id: typing.Optional[str] = OMIT,
        merchant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccountUpdaterRealTimeResponse:
        """
        Returns the update result

        Parameters
        ----------
        token_id : str
            Card Token identifier

        bt_merchant_id : typing.Optional[str]
            Tenant merchant the request acts as. The card token is read within this merchant's scope and the updated token is associated with it. Responds 404 if the merchant does not exist in the tenant.

        expiration_year : typing.Optional[int]
            The 4-digit expiration year of the account number. Not required if the card token already stores this value.

        expiration_month : typing.Optional[int]
            The 2-digit expiration month of the account number. Not required if the card token already stores this value.

        deduplicate_token : typing.Optional[bool]
            Whether deduplication should be enabled when creating the new token. Uses the value of the Deduplicate Tokens setting on the tenant if not set.

        configuration_merchant_id : typing.Optional[str]
            Tenant merchant whose provider configuration is used for this request. Selects configuration only; it does not scope token access or associate the new token with the merchant. Takes precedence over merchant_id; defaults to the BT-MERCHANT-ID header merchant, then the tenant-level configuration.

        merchant_id : typing.Optional[str]
            Deprecated: use configuration_merchant_id instead. Legacy alias kept for backward compatibility with lower precedence. Selects configuration only.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccountUpdaterRealTimeResponse
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.account_updater.real_time.invoke(
                token_id="9a420b15-ddfe-4793-9466-48f53520e47c",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.invoke(
            token_id=token_id,
            bt_merchant_id=bt_merchant_id,
            expiration_year=expiration_year,
            expiration_month=expiration_month,
            deduplicate_token=deduplicate_token,
            configuration_merchant_id=configuration_merchant_id,
            merchant_id=merchant_id,
            request_options=request_options,
        )
        return _response.data
