# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgenticCardIssuerCountry(UniversalBaseModel):
    """
    Card issuer country details
    """

    alpha2: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 3166-1 alpha-2 country code
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Country name
    """

    numeric: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 3166-1 numeric country code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
