# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .allowance_verification_method_type import AllowanceVerificationMethodType


class AllowanceVerificationMethod(UniversalBaseModel):
    id: str
    type: AllowanceVerificationMethodType
    value: str = pydantic.Field()
    """
    Masked destination or issuer-provided display label.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
