# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .allowance_verification_next_action import AllowanceVerificationNextAction
from .allowance_verification_response_provider import AllowanceVerificationResponseProvider
from .allowance_verification_response_rail import AllowanceVerificationResponseRail
from .allowance_verification_response_status import AllowanceVerificationResponseStatus


class AllowanceVerificationResponse(UniversalBaseModel):
    status: AllowanceVerificationResponseStatus
    rail: AllowanceVerificationResponseRail
    provider: AllowanceVerificationResponseProvider
    next_action: typing.Optional[AllowanceVerificationNextAction] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
