# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PollAuthorizeConnectionRequest(UniversalBaseModel):
    action: typing.Literal["poll"] = "poll"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RestartAuthorizeConnectionRequest(UniversalBaseModel):
    action: typing.Literal["restart"] = "restart"
    permissions: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PresentAuthorizeConnectionRequest(UniversalBaseModel):
    action: typing.Literal["present"] = "present"
    credential: typing.Dict[str, typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


AuthorizeConnectionRequest = typing_extensions.Annotated[
    typing.Union[PollAuthorizeConnectionRequest, RestartAuthorizeConnectionRequest, PresentAuthorizeConnectionRequest],
    pydantic.Field(discriminator="action"),
]
