# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AuthorizeConnectionRequestRestart(UniversalBaseModel):
    """
    Re-run the ceremony on this connection. The single entry point for repairing a broken authorization and for widening permissions; the connection id and every payment method and allowance referencing it survive. The existing authorization stays usable until the new one succeeds.
    """

    permissions: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
