# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .network_status_detail import NetworkStatusDetail


class CardNetworkStatus(UniversalBaseModel):
    visa: typing.Optional[NetworkStatusDetail] = None
    mastercard: typing.Optional[NetworkStatusDetail] = None
    amex: typing.Optional[NetworkStatusDetail] = None
    discover: typing.Optional[NetworkStatusDetail] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
