# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ConnectionNextAction(UniversalBaseModel):
    """
    Present only while a ceremony is outstanding. A grant method whose ceremony is `none` never returns this field, and its absence together with `status_details.action: none` means there is nothing to do.
    """

    type: typing.Literal["redirect"] = "redirect"
    purpose: str = pydantic.Field()
    """
    Why the principal is being sent to the provider. Open by design: a provider may introduce a ceremony purpose without a breaking change to this schema.
    """

    uri: str
    uri_type: typing.Literal["WEB_URI"] = "WEB_URI"
    expires_at: typing.Optional[dt.datetime] = None
    poll_after_seconds: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
