# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .credentials_card import CredentialsCard
from .credentials_mpp import CredentialsMpp
from .credentials_spt import CredentialsSpt


class Credentials(UniversalBaseModel):
    """
    Credential payload for the instruction. Exactly one of `card`, `spt`, or `mpp` is present:
    `card` for Visa/Mastercard virtual card credentials, `spt` for Stripe shared payment token
    instructions (raw mode), `mpp` for Stripe instructions created with an MPP challenge.
    """

    card: typing.Optional[CredentialsCard] = None
    spt: typing.Optional[CredentialsSpt] = pydantic.Field(default=None)
    """
    Stripe shared payment token (raw mode)
    """

    mpp: typing.Optional[CredentialsMpp] = pydantic.Field(default=None)
    """
    MPP credential (MPP mode)
    """

    expires_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
