# This file was auto-generated by Fern from our API Definition.

import typing

DeliveryMethod = typing.Union[
    typing.Literal["no-delivery", "address-billing", "address-on-file", "address-other", "pickup", "electronic"],
    typing.Any,
]
