# This file was auto-generated by Fern from our API Definition.

import typing

EnrollmentProvider = typing.Union[
    typing.Literal["visa", "mastercard", "stripe", "visa-mock", "mastercard-mock", "stripe-mock"], typing.Any
]
