# This file was auto-generated by Fern from our API Definition.

import typing

EnrollmentStatus = typing.Union[
    typing.Literal["pending_verification", "active", "suspended", "deleted", "failed"], typing.Any
]
