# This file was auto-generated by Fern from our API Definition.

import typing

InstructionStatus = typing.Union[
    typing.Literal["active", "pending", "pending_verification", "approved", "cancelled", "expired"], typing.Any
]
