# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .amount import Amount
from .instruction_status import InstructionStatus
from .recurring import Recurring


class Instruction(UniversalBaseModel):
    id: typing.Optional[str] = None
    enrollment_id: typing.Optional[str] = None
    status: typing.Optional[InstructionStatus] = None
    amount: typing.Optional[Amount] = None
    description: typing.Optional[str] = None
    expires_at: typing.Optional[dt.datetime] = None
    recurring: typing.Optional[Recurring] = None
    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
