# This file was auto-generated by Fern from our API Definition.

import typing

MppSourceType = typing.Union[
    typing.Literal["token", "network_token", "apple_pay", "google_pay", "visa_intelligent_commerce"], typing.Any
]
