# This file was auto-generated by Fern from our API Definition.

import typing

PaymentCredentialMetadataFormat = typing.Union[typing.Literal["card", "network-token", "identifier", "mpp"], typing.Any]
