# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_method_instrument_display import PaymentMethodInstrumentDisplay
from .payment_method_instrument_type import PaymentMethodInstrumentType


class PaymentMethodInstrument(UniversalBaseModel):
    type: PaymentMethodInstrumentType = pydantic.Field()
    """
    The set a payment method can actually carry today. `stablecoin_wallet` and `bnpl_account` are listed on ConnectionInstrument and can be enumerated, but no rail funds them yet, so sourcing one fails before a payment method exists. `other` is an instrument the provider offers that Basis Theory could not classify.
    """

    provider: str
    display: PaymentMethodInstrumentDisplay = pydantic.Field()
    """
    Shaped by `type`; empty for `other`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
