# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_credential_credential_format import PaymentCredentialCredentialFormat
from .payment_credential_credential_value import PaymentCredentialCredentialValue


class PaymentCredentialCredential(UniversalBaseModel):
    format: PaymentCredentialCredentialFormat = pydantic.Field()
    """
    card, network-token, and identifier are direct API credentials. mpp is a complete base64url Machine Payments Protocol credential for an Authorization Payment header.
    """

    value: PaymentCredentialCredentialValue = pydantic.Field()
    """
    Spendable credential value in the requested format. Returned once and never persisted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
