# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .proxy_transform import ProxyTransform


class PendingProxy(UniversalBaseModel):
    destination_url: typing.Optional[str] = None
    configuration: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    require_auth: typing.Optional[bool] = None
    request_transforms: typing.Optional[typing.List[ProxyTransform]] = None
    response_transforms: typing.Optional[typing.List[ProxyTransform]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
