# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .card_network_status import CardNetworkStatus


class ServiceStatus(UniversalBaseModel):
    status: typing.Optional[str] = None
    providers: typing.Optional[typing.List[str]] = None
    card_network_status: typing.Optional[CardNetworkStatus] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
