# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SharedPaymentConsumer(UniversalBaseModel):
    email: str
    id: typing.Optional[str] = None
    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Officially assigned ISO 3166-1 alpha-2 code. Lowercase request values are normalized.
    """

    language_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    BCP 47 language tag. Canonicalized on input (for example, `EN-us` becomes `en-US`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
