# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SharedPaymentAmount(UniversalBaseModel):
    value: str = pydantic.Field()
    """
    Major-unit decimal amount. Precision follows the currency's ISO 4217 minor unit and responses are canonicalized to that precision.
    """

    currency: str = pydantic.Field()
    """
    Current ISO 4217 code with a numeric minor-unit definition. Lowercase request values are normalized.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
