# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .shared_payment_rail_base_agentic_token_provider import SharedPaymentRailBaseAgenticTokenProvider


class AgenticTokenSharedPaymentRailBase(UniversalBaseModel):
    rail: typing.Literal["agentic-token"] = "agentic-token"
    provider: SharedPaymentRailBaseAgenticTokenProvider
    provider_ids: typing.Optional[typing.Dict[str, str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SptSharedPaymentRailBase(UniversalBaseModel):
    rail: typing.Literal["spt"] = "spt"
    provider: typing.Literal["stripe"] = "stripe"
    provider_ids: typing.Optional[typing.Dict[str, str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class VirtualCardSharedPaymentRailBase(UniversalBaseModel):
    rail: typing.Literal["virtual-card"] = "virtual-card"
    provider: typing.Literal["link"] = "link"
    provider_ids: typing.Optional[typing.Dict[str, str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SharedPaymentRailBase = typing_extensions.Annotated[
    typing.Union[AgenticTokenSharedPaymentRailBase, SptSharedPaymentRailBase, VirtualCardSharedPaymentRailBase],
    pydantic.Field(discriminator="rail"),
]
