# This file was auto-generated by Fern from our API Definition.

import typing

SharedPaymentProviderErrorProvider = typing.Union[
    typing.Literal["vic", "agentpay", "stripe", "link", "stripe_link"], typing.Any
]
