# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .shared_payment_card_display import SharedPaymentCardDisplay
from .shared_payment_card_issuer import SharedPaymentCardIssuer
from .shared_payment_card_issuer_country import SharedPaymentCardIssuerCountry


class SharedPaymentCard(UniversalBaseModel):
    brand: typing.Optional[str] = pydantic.Field(default=None)
    """
    Card network reported by the vault. `agentic-token` rails require `visa` or `mastercard`; the `spt` rail accepts any network Stripe supports, so treat this as an open string rather than a closed set.
    """

    bin: typing.Optional[str] = None
    last4: typing.Optional[str] = None
    expiration_month: typing.Optional[int] = None
    expiration_year: typing.Optional[int] = None
    funding: typing.Optional[str] = None
    issuer: typing.Optional[SharedPaymentCardIssuer] = None
    issuer_country: typing.Optional[SharedPaymentCardIssuerCountry] = None
    segment: typing.Optional[str] = None
    type: typing.Optional[str] = None
    display: typing.Optional[SharedPaymentCardDisplay] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
