# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .shared_payment_provider_error import SharedPaymentProviderError
from .shared_payment_provider_error_list_pagination import SharedPaymentProviderErrorListPagination


class SharedPaymentProviderErrorList(UniversalBaseModel):
    data: typing.Optional[typing.List[SharedPaymentProviderError]] = None
    pagination: typing.Optional[SharedPaymentProviderErrorListPagination] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
