# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .merchant_details import MerchantDetails
from .merchant_services import MerchantServices


class TenantMerchant(UniversalBaseModel):
    id: typing.Optional[str] = None
    tenant_id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    details: typing.Optional[MerchantDetails] = None
    services: typing.Optional[MerchantServices] = None
    created_by: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    modified_by: typing.Optional[str] = None
    modified_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
