# This file was auto-generated by Fern from our API Definition.

import typing

TransactionType = typing.Union[
    typing.Literal["purchase", "authorization", "capture", "refund", "reversal", "verification", "chargeback", "fraud"],
    typing.Any,
]
