# This file was auto-generated by Fern from our API Definition.

import typing

VerificationResponseStatus = typing.Union[
    typing.Literal["approved", "challenge", "otp_sent", "device_bound", "passkey_required", "verified"], typing.Any
]
