# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .verification_response_brand import VerificationResponseBrand
from .verification_response_methods_item import VerificationResponseMethodsItem
from .verification_response_passkey_context import VerificationResponsePasskeyContext
from .verification_response_status import VerificationResponseStatus


class VerificationResponse(UniversalBaseModel):
    status: typing.Optional[VerificationResponseStatus] = None
    methods: typing.Optional[typing.List[VerificationResponseMethodsItem]] = None
    passkey_context: typing.Optional[VerificationResponsePasskeyContext] = pydantic.Field(default=None)
    """
    Visa passkey/FIDO context for device binding or authentication
    """

    brand: typing.Optional[VerificationResponseBrand] = pydantic.Field(default=None)
    """
    Card network brand (present in Mastercard responses)
    """

    auth_context: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Mastercard authentication context
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
