# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .verify_allowance_request_submit_session_session_context import VerifyAllowanceRequestSubmitSessionSessionContext


class VerifyAllowanceRequestSubmitSession(UniversalBaseModel):
    rail: typing.Literal["agentic-token"] = "agentic-token"
    provider: typing.Literal["vic"] = "vic"
    session_context: VerifyAllowanceRequestSubmitSessionSessionContext = pydantic.Field()
    """
    Secure session returned by Visa's hosted iframe after `passkey_session`. The original device context and display name are retained server-side.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
