# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .verify_allowance_request_start_device_context import VerifyAllowanceRequestStartDeviceContext
from .verify_allowance_request_start_provider import VerifyAllowanceRequestStartProvider
from .verify_allowance_request_start_rail import VerifyAllowanceRequestStartRail


class VerifyAllowanceRequestStart(UniversalBaseModel):
    rail: VerifyAllowanceRequestStartRail
    provider: VerifyAllowanceRequestStartProvider
    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Application or agent name shown on network verification screens, including approval and return-to-application messages.
    """

    device_context: typing.Optional[VerifyAllowanceRequestStartDeviceContext] = pydantic.Field(default=None)
    """
    Browser/device data captured once on Visa `start`. Only `language_code` and `time_zone` are validated; every other property is forwarded to Visa unchanged. The API retains it for `submit_session`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
