# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .verification_response_passkey_context_action import VerificationResponsePasskeyContextAction
from .verification_response_passkey_context_auth_preferences import VerificationResponsePasskeyContextAuthPreferences
from .verification_response_passkey_context_display_context import VerificationResponsePasskeyContextDisplayContext
from .verification_response_passkey_context_platform_type import VerificationResponsePasskeyContextPlatformType


class VerificationResponsePasskeyContext(UniversalBaseModel):
    """
    Visa passkey/FIDO context for device binding or authentication
    """

    endpoint: typing.Optional[str] = None
    identifier: typing.Optional[str] = None
    payload: typing.Optional[str] = None
    action: typing.Optional[VerificationResponsePasskeyContextAction] = None
    platform_type: typing.Optional[VerificationResponsePasskeyContextPlatformType] = None
    auth_preferences: typing.Optional[VerificationResponsePasskeyContextAuthPreferences] = None
    display_context: typing.Optional[VerificationResponsePasskeyContextDisplayContext] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
