# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .verify_allowance_request_complete_provider import VerifyAllowanceRequestCompleteProvider
from .verify_allowance_request_complete_rail import VerifyAllowanceRequestCompleteRail


class VerifyAllowanceRequestComplete(UniversalBaseModel):
    rail: VerifyAllowanceRequestCompleteRail
    provider: VerifyAllowanceRequestCompleteProvider

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
