# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VerifyAllowanceRequestStartDeviceContext(UniversalBaseModel):
    """
    Browser/device data captured once on Visa `start`. Only `language_code` and `time_zone` are validated; every other property is forwarded to Visa unchanged. The API retains it for `submit_session`.
    """

    language_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    BCP 47 language tag. Canonicalized on input (for example, `EN-us` becomes `en-US`); underscore locales such as `en_US` are rejected.
    """

    time_zone: typing.Optional[str] = pydantic.Field(default=None)
    """
    IANA time zone identifier, such as `America/New_York`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
