# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_response_status import WebhookResponseStatus
import typing
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class WebhookResponse(UniversalBaseModel):
    id: str
    tenant_id: str
    status: WebhookResponseStatus
    name: str
    url: str
    events: typing.List[str]
    created_by: str
    created_at: dt.datetime
    modified_by: str
    modified_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
