# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .webhook_list_response_pagination import WebhookListResponsePagination
import typing
from .webhook_response import WebhookResponse
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class WebhookListResponse(UniversalBaseModel):
    pagination: WebhookListResponsePagination
    data: typing.List[WebhookResponse]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
