# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.card_network_info import CardNetworkInfo
from ...types.merchant_details import MerchantDetails
from ...types.tenant_merchant import TenantMerchant
from .raw_client import AsyncRawMerchantsClient, RawMerchantsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MerchantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMerchantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMerchantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMerchantsClient
        """
        return self._raw_client

    def list(
        self,
        tenant_id: str,
        *,
        page: typing.Optional[int] = None,
        start: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[TenantMerchant]:
        """
        Parameters
        ----------
        tenant_id : str

        page : typing.Optional[int]

        start : typing.Optional[str]

        size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[TenantMerchant]
            Success

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        response = client.tenants.merchants.list(
            tenant_id="tenantId",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(tenant_id, page=page, start=start, size=size, request_options=request_options)

    def create(
        self,
        tenant_id: str,
        *,
        name: str,
        details: MerchantDetails,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        name : str

        details : MerchantDetails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        from basis_theory import BasisTheory, MerchantDetails

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.tenants.merchants.create(
            tenant_id="tenantId",
            name="name",
            details=MerchantDetails(),
        )
        """
        _response = self._raw_client.create(tenant_id, name=name, details=details, request_options=request_options)
        return _response.data

    def get(
        self, tenant_id: str, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.tenants.merchants.get(
            tenant_id="tenantId",
            merchant_id="merchantId",
        )
        """
        _response = self._raw_client.get(tenant_id, merchant_id, request_options=request_options)
        return _response.data

    def delete(
        self, tenant_id: str, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.tenants.merchants.delete(
            tenant_id="tenantId",
            merchant_id="merchantId",
        )
        """
        _response = self._raw_client.delete(tenant_id, merchant_id, request_options=request_options)
        return _response.data

    def update(
        self,
        tenant_id: str,
        merchant_id: str,
        *,
        name: str,
        details: MerchantDetails,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        name : str

        details : MerchantDetails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        from basis_theory import BasisTheory, MerchantDetails

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.tenants.merchants.update(
            tenant_id="tenantId",
            merchant_id="merchantId",
            name="name",
            details=MerchantDetails(),
        )
        """
        _response = self._raw_client.update(
            tenant_id, merchant_id, name=name, details=details, request_options=request_options
        )
        return _response.data

    def request_onboarding(
        self,
        tenant_id: str,
        merchant_id: str,
        *,
        account_updater: typing.Optional[typing.Sequence[str]] = OMIT,
        network_token: typing.Optional[typing.Sequence[str]] = OMIT,
        agentic_commerce: typing.Optional[typing.Sequence[str]] = OMIT,
        card_network_info: typing.Optional[CardNetworkInfo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        account_updater : typing.Optional[typing.Sequence[str]]

        network_token : typing.Optional[typing.Sequence[str]]

        agentic_commerce : typing.Optional[typing.Sequence[str]]

        card_network_info : typing.Optional[CardNetworkInfo]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.tenants.merchants.request_onboarding(
            tenant_id="tenantId",
            merchant_id="merchantId",
        )
        """
        _response = self._raw_client.request_onboarding(
            tenant_id,
            merchant_id,
            account_updater=account_updater,
            network_token=network_token,
            agentic_commerce=agentic_commerce,
            card_network_info=card_network_info,
            request_options=request_options,
        )
        return _response.data


class AsyncMerchantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMerchantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMerchantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMerchantsClient
        """
        return self._raw_client

    async def list(
        self,
        tenant_id: str,
        *,
        page: typing.Optional[int] = None,
        start: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[TenantMerchant]:
        """
        Parameters
        ----------
        tenant_id : str

        page : typing.Optional[int]

        start : typing.Optional[str]

        size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[TenantMerchant]
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.tenants.merchants.list(
                tenant_id="tenantId",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            tenant_id, page=page, start=start, size=size, request_options=request_options
        )

    async def create(
        self,
        tenant_id: str,
        *,
        name: str,
        details: MerchantDetails,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        name : str

        details : MerchantDetails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory, MerchantDetails

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tenants.merchants.create(
                tenant_id="tenantId",
                name="name",
                details=MerchantDetails(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            tenant_id, name=name, details=details, request_options=request_options
        )
        return _response.data

    async def get(
        self, tenant_id: str, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tenants.merchants.get(
                tenant_id="tenantId",
                merchant_id="merchantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(tenant_id, merchant_id, request_options=request_options)
        return _response.data

    async def delete(
        self, tenant_id: str, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tenants.merchants.delete(
                tenant_id="tenantId",
                merchant_id="merchantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(tenant_id, merchant_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        tenant_id: str,
        merchant_id: str,
        *,
        name: str,
        details: MerchantDetails,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        name : str

        details : MerchantDetails

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory, MerchantDetails

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tenants.merchants.update(
                tenant_id="tenantId",
                merchant_id="merchantId",
                name="name",
                details=MerchantDetails(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            tenant_id, merchant_id, name=name, details=details, request_options=request_options
        )
        return _response.data

    async def request_onboarding(
        self,
        tenant_id: str,
        merchant_id: str,
        *,
        account_updater: typing.Optional[typing.Sequence[str]] = OMIT,
        network_token: typing.Optional[typing.Sequence[str]] = OMIT,
        agentic_commerce: typing.Optional[typing.Sequence[str]] = OMIT,
        card_network_info: typing.Optional[CardNetworkInfo] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantMerchant:
        """
        Parameters
        ----------
        tenant_id : str

        merchant_id : str

        account_updater : typing.Optional[typing.Sequence[str]]

        network_token : typing.Optional[typing.Sequence[str]]

        agentic_commerce : typing.Optional[typing.Sequence[str]]

        card_network_info : typing.Optional[CardNetworkInfo]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantMerchant
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.tenants.merchants.request_onboarding(
                tenant_id="tenantId",
                merchant_id="merchantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.request_onboarding(
            tenant_id,
            merchant_id,
            account_updater=account_updater,
            network_token=network_token,
            agentic_commerce=agentic_commerce,
            card_network_info=card_network_info,
            request_options=request_options,
        )
        return _response.data
