# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from .....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .....types.mpp_stripe_challenge import MppStripeChallenge


class CreateInstructionRequestMpp(UniversalBaseModel):
    """
    MPP mode — provide the merchant's MPP challenge to receive an MPP credential from the
    credentials endpoint instead of a raw shared payment token ID. The challenge must carry
    Stripe values (`method: stripe`). Only valid for `spt` (Stripe) enrollments.
    """

    challenge: MppStripeChallenge

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
