# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawTenantsClient, RawTenantsClient

if typing.TYPE_CHECKING:
    from .connections.client import AsyncConnectionsClient, ConnectionsClient
    from .invitations.client import AsyncInvitationsClient, InvitationsClient
    from .members.client import AsyncMembersClient, MembersClient
    from .owner.client import AsyncOwnerClient, OwnerClient
    from .security_contact.client import AsyncSecurityContactClient, SecurityContactClient
    from .self_.client import AsyncSelfClient, SelfClient


class TenantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTenantsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._security_contact: typing.Optional[SecurityContactClient] = None
        self._connections: typing.Optional[ConnectionsClient] = None
        self._invitations: typing.Optional[InvitationsClient] = None
        self._members: typing.Optional[MembersClient] = None
        self._owner: typing.Optional[OwnerClient] = None
        self._self_: typing.Optional[SelfClient] = None

    @property
    def with_raw_response(self) -> RawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTenantsClient
        """
        return self._raw_client

    @property
    def security_contact(self):
        if self._security_contact is None:
            from .security_contact.client import SecurityContactClient  # noqa: E402

            self._security_contact = SecurityContactClient(client_wrapper=self._client_wrapper)
        return self._security_contact

    @property
    def connections(self):
        if self._connections is None:
            from .connections.client import ConnectionsClient  # noqa: E402

            self._connections = ConnectionsClient(client_wrapper=self._client_wrapper)
        return self._connections

    @property
    def invitations(self):
        if self._invitations is None:
            from .invitations.client import InvitationsClient  # noqa: E402

            self._invitations = InvitationsClient(client_wrapper=self._client_wrapper)
        return self._invitations

    @property
    def members(self):
        if self._members is None:
            from .members.client import MembersClient  # noqa: E402

            self._members = MembersClient(client_wrapper=self._client_wrapper)
        return self._members

    @property
    def owner(self):
        if self._owner is None:
            from .owner.client import OwnerClient  # noqa: E402

            self._owner = OwnerClient(client_wrapper=self._client_wrapper)
        return self._owner

    @property
    def self_(self):
        if self._self_ is None:
            from .self_.client import SelfClient  # noqa: E402

            self._self_ = SelfClient(client_wrapper=self._client_wrapper)
        return self._self_


class AsyncTenantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTenantsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._security_contact: typing.Optional[AsyncSecurityContactClient] = None
        self._connections: typing.Optional[AsyncConnectionsClient] = None
        self._invitations: typing.Optional[AsyncInvitationsClient] = None
        self._members: typing.Optional[AsyncMembersClient] = None
        self._owner: typing.Optional[AsyncOwnerClient] = None
        self._self_: typing.Optional[AsyncSelfClient] = None

    @property
    def with_raw_response(self) -> AsyncRawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTenantsClient
        """
        return self._raw_client

    @property
    def security_contact(self):
        if self._security_contact is None:
            from .security_contact.client import AsyncSecurityContactClient  # noqa: E402

            self._security_contact = AsyncSecurityContactClient(client_wrapper=self._client_wrapper)
        return self._security_contact

    @property
    def connections(self):
        if self._connections is None:
            from .connections.client import AsyncConnectionsClient  # noqa: E402

            self._connections = AsyncConnectionsClient(client_wrapper=self._client_wrapper)
        return self._connections

    @property
    def invitations(self):
        if self._invitations is None:
            from .invitations.client import AsyncInvitationsClient  # noqa: E402

            self._invitations = AsyncInvitationsClient(client_wrapper=self._client_wrapper)
        return self._invitations

    @property
    def members(self):
        if self._members is None:
            from .members.client import AsyncMembersClient  # noqa: E402

            self._members = AsyncMembersClient(client_wrapper=self._client_wrapper)
        return self._members

    @property
    def owner(self):
        if self._owner is None:
            from .owner.client import AsyncOwnerClient  # noqa: E402

            self._owner = AsyncOwnerClient(client_wrapper=self._client_wrapper)
        return self._owner

    @property
    def self_(self):
        if self._self_ is None:
            from .self_.client import AsyncSelfClient  # noqa: E402

            self._self_ = AsyncSelfClient(client_wrapper=self._client_wrapper)
        return self._self_
