# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.event import Event
from ..types.event_page import EventPage
from .raw_client import AsyncRawEventsClient, RawEventsClient


class EventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEventsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
        start: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        type: typing.Optional[str] = None,
        trace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Event, EventPage]:
        """
        Requires event:read. Tenant identity comes from trusted API-key authentication. History is limited by log_history_limit (24 hours by default, at most 30 days). Windows reaching outside the visible history are clamped to it rather than rejected. No secondary failover or portal JWT support. SDK callers supply data.<path> filters as literal keys through the SDK's per-request query-parameter options, not as a filters request field.

        Parameters
        ----------
        start_date : typing.Optional[dt.datetime]
            Inclusive timestamp; defaults to 24 hours before end_date, shortened to tenant entitlement. An earlier value is raised to the oldest visible instant. ISO 8601 with timezone, at most millisecond precision. Must not be after end_date.

        end_date : typing.Optional[dt.datetime]
            Exclusive timestamp; defaults to request time. A future value is lowered to request time. A window with no visible history returns an empty page.

        start : typing.Optional[str]
            Opaque cursor from pagination.next. Bound to tenant, filters, window, page size, and configured collection/index generation.

        size : typing.Optional[int]
            Maximum unique events returned. A short page may have a next cursor.

        type : typing.Optional[str]
            Exact event type.

        trace_id : typing.Optional[str]
            Exact trace ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Event, EventPage]
            Newest-first event history. Asynchronous visibility; duplicate suppression is page-local. Follow next until null, including short pages. Continuations preserve the first page's clamped bounds while excluding newly expired history or history hidden by an entitlement reduction.

        Examples
        --------
        import datetime

        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        response = client.events.list(
            start_date=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            end_date=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            start="start",
            size=1,
            type="type",
            trace_id="trace_id",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            start_date=start_date,
            end_date=end_date,
            start=start,
            size=size,
            type=type,
            trace_id=trace_id,
            request_options=request_options,
        )


class AsyncEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEventsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        start_date: typing.Optional[dt.datetime] = None,
        end_date: typing.Optional[dt.datetime] = None,
        start: typing.Optional[str] = None,
        size: typing.Optional[int] = None,
        type: typing.Optional[str] = None,
        trace_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Event, EventPage]:
        """
        Requires event:read. Tenant identity comes from trusted API-key authentication. History is limited by log_history_limit (24 hours by default, at most 30 days). Windows reaching outside the visible history are clamped to it rather than rejected. No secondary failover or portal JWT support. SDK callers supply data.<path> filters as literal keys through the SDK's per-request query-parameter options, not as a filters request field.

        Parameters
        ----------
        start_date : typing.Optional[dt.datetime]
            Inclusive timestamp; defaults to 24 hours before end_date, shortened to tenant entitlement. An earlier value is raised to the oldest visible instant. ISO 8601 with timezone, at most millisecond precision. Must not be after end_date.

        end_date : typing.Optional[dt.datetime]
            Exclusive timestamp; defaults to request time. A future value is lowered to request time. A window with no visible history returns an empty page.

        start : typing.Optional[str]
            Opaque cursor from pagination.next. Bound to tenant, filters, window, page size, and configured collection/index generation.

        size : typing.Optional[int]
            Maximum unique events returned. A short page may have a next cursor.

        type : typing.Optional[str]
            Exact event type.

        trace_id : typing.Optional[str]
            Exact trace ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Event, EventPage]
            Newest-first event history. Asynchronous visibility; duplicate suppression is page-local. Follow next until null, including short pages. Continuations preserve the first page's clamped bounds while excluding newly expired history or history hidden by an entitlement reduction.

        Examples
        --------
        import asyncio
        import datetime

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.events.list(
                start_date=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                end_date=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                start="start",
                size=1,
                type="type",
                trace_id="trace_id",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            start_date=start_date,
            end_date=end_date,
            start=start,
            size=size,
            type=type,
            trace_id=trace_id,
            request_options=request_options,
        )
