# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
from .googlepay.client import GooglepayClient
from ..core.client_wrapper import AsyncClientWrapper
from .googlepay.client import AsyncGooglepayClient


class ConnectionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.googlepay = GooglepayClient(client_wrapper=self._client_wrapper)


class AsyncConnectionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        self.googlepay = AsyncGooglepayClient(client_wrapper=self._client_wrapper)
