# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.apple_pay_merchant_certificates import ApplePayMerchantCertificates
from .raw_client import AsyncRawCertificatesClient, RawCertificatesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CertificatesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCertificatesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCertificatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCertificatesClient
        """
        return self._raw_client

    def get(
        self, merchant_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApplePayMerchantCertificates:
        """
        Parameters
        ----------
        merchant_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApplePayMerchantCertificates
            Success

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.apple_pay.merchant.certificates.get(
            merchant_id="merchantId",
            id="id",
        )
        """
        _response = self._raw_client.get(merchant_id, id, request_options=request_options)
        return _response.data

    def delete(self, merchant_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        merchant_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.apple_pay.merchant.certificates.delete(
            merchant_id="merchantId",
            id="id",
        )
        """
        _response = self._raw_client.delete(merchant_id, id, request_options=request_options)
        return _response.data

    def create(
        self,
        merchant_id: str,
        *,
        merchant_certificate_data: typing.Optional[str] = OMIT,
        merchant_certificate_password: typing.Optional[str] = OMIT,
        payment_processor_certificate_data: typing.Optional[str] = OMIT,
        payment_processor_certificate_password: typing.Optional[str] = OMIT,
        domain: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApplePayMerchantCertificates:
        """
        Parameters
        ----------
        merchant_id : str

        merchant_certificate_data : typing.Optional[str]

        merchant_certificate_password : typing.Optional[str]

        payment_processor_certificate_data : typing.Optional[str]

        payment_processor_certificate_password : typing.Optional[str]

        domain : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApplePayMerchantCertificates
            Success

        Examples
        --------
        from basis_theory import BasisTheory

        client = BasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )
        client.apple_pay.merchant.certificates.create(
            merchant_id="merchantId",
        )
        """
        _response = self._raw_client.create(
            merchant_id,
            merchant_certificate_data=merchant_certificate_data,
            merchant_certificate_password=merchant_certificate_password,
            payment_processor_certificate_data=payment_processor_certificate_data,
            payment_processor_certificate_password=payment_processor_certificate_password,
            domain=domain,
            request_options=request_options,
        )
        return _response.data


class AsyncCertificatesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCertificatesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCertificatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCertificatesClient
        """
        return self._raw_client

    async def get(
        self, merchant_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ApplePayMerchantCertificates:
        """
        Parameters
        ----------
        merchant_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApplePayMerchantCertificates
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.apple_pay.merchant.certificates.get(
                merchant_id="merchantId",
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(merchant_id, id, request_options=request_options)
        return _response.data

    async def delete(
        self, merchant_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        merchant_id : str

        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.apple_pay.merchant.certificates.delete(
                merchant_id="merchantId",
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(merchant_id, id, request_options=request_options)
        return _response.data

    async def create(
        self,
        merchant_id: str,
        *,
        merchant_certificate_data: typing.Optional[str] = OMIT,
        merchant_certificate_password: typing.Optional[str] = OMIT,
        payment_processor_certificate_data: typing.Optional[str] = OMIT,
        payment_processor_certificate_password: typing.Optional[str] = OMIT,
        domain: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ApplePayMerchantCertificates:
        """
        Parameters
        ----------
        merchant_id : str

        merchant_certificate_data : typing.Optional[str]

        merchant_certificate_password : typing.Optional[str]

        payment_processor_certificate_data : typing.Optional[str]

        payment_processor_certificate_password : typing.Optional[str]

        domain : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApplePayMerchantCertificates
            Success

        Examples
        --------
        import asyncio

        from basis_theory import AsyncBasisTheory

        client = AsyncBasisTheory(
            correlation_id="YOUR_CORRELATION_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.apple_pay.merchant.certificates.create(
                merchant_id="merchantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            merchant_id,
            merchant_certificate_data=merchant_certificate_data,
            merchant_certificate_password=merchant_certificate_password,
            payment_processor_certificate_data=payment_processor_certificate_data,
            payment_processor_certificate_password=payment_processor_certificate_password,
            domain=domain,
            request_options=request_options,
        )
        return _response.data
