name: Security Scan

on:
  schedule:
    - cron: '0 12 * * 1' # 12pm UTC every Monday
  workflow_dispatch:

jobs:
  code-scan:
    name: SAST scan
    uses: Basis-Theory/security-workflows/.github/workflows/code-scan.yml@master
    secrets: inherit
    with:
      scan-directory: $GITHUB_WORKSPACE
      app-name: python-sdk

  dependency-scan:
    name: SCA scan
    needs: build
    uses: Basis-Theory/security-workflows/.github/workflows/dependency-scan.yml@master
    secrets: inherit
    with:
      scan-directory: $GITHUB_WORKSPACE
      app-name: python-sdk